version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.se_tlundstr3.integrations:FirstSample
  packages:
  - name: EdgeSE_tlundstr3
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: t2utilities.simulator:getProductSales
  packages:
  - name: T2Utilities
    version: "1.0"
- serviceName: pub.client:restClient
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
- serviceName: edge.se_tlundstr3.integrations:Products
  packages:
  - name: EdgeSE_tlundstr3
    version: "1.0"
  - name: T2Utilities
    version: "1.0"
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.473
packages:
- name: EdgeSE_tlundstr3
  gitServerName: tlundstr_git
  gitUrl: https://github.com/tlundstr/EdgeSE_tlundstr3
  gitUsername: tlundstr
  gitToken: edge.scaffolding.EdgeSE_tlundstr3.tlundstr_git.gitToken
  gitBranch: main
- name: T2Utilities
  gitServerName: tlundstr_git
  gitUrl: https://github.com/tlundstr
  gitUsername: tlundstr
  gitToken: edge.scaffolding.T2Utilities.tlundstr_git.gitToken
  gitBranch: master
